let shopItemsData = [
  {
    id: "jfhgbvnscs",
    name: "Hamburguer",
    subtitle: "Meet",
    price: 45,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/hamburguer-1.jpg",
    n: 0,
  },
  {
    id: "ioytrhndcv",
    name: "Hamburguer",
    subtitle: "Chicken",
    price: 100,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/hamburguer-2.jpg",
    n: 1,
  },
  {
    id: "wuefbncxbsn",
    name: "Hamburguer",
    subtitle: "Pork",
    price: 25,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/hamburguer-3.jpg",
    n: 2,
  },
  {
    id: "thyfhcbcv",
    name: "Hamburguer",
    subtitle: "Turkey",
    price: 300,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/hamburguer-4.jpg",
    n: 3,
  },
  {
    id: "aaabbbc",
    name: "Hamburguer",
    subtitle: "Vegetable",
    price: 65,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/hamburguer-5.jpg",
    n: 4,
  },

/* block 2rd group */

  {
    id: "abcdwfr",
    name: "Hotdog",
    subtitle: "Meet",
    price: 45,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/hotdog-1.jpg",
    n: 5,
  },
  {
    id: "bvfgfre",
    name: "Hotdog",
    subtitle: "Chicken",
    price: 100,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/hotdog-2.jpg",
    n: 6,
  },
  {
    id: "bfgdtk",
    name: "Hotdog",
    subtitle: "Pork",
    price: 25,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/hotdog-3.jpg",
    n: 7,
  },
  {
    id: "bdaswsd",
    name: "Hotdog",
    subtitle: "Turkey",
    price: 300,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/hotdog-4.jpg",
    n: 8,
  },
  {
    id: "bdstrs",
    name: "Hotdog",
    subtitle: "Veggie",
    price: 65,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/hotdog-5.jpg",
    n: 9,
  },
  /* block 3rd group */
  {
    id: "chhgf",
    name: "Sandwiches",
    subtitle: "Meet",
    price: 45,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/sandwiches-1.jpg",
    n: 10,
  },
  {
    id: "chytghh",
    name: "Sandwiches",
    subtitle: "Chicken",
    price: 100,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/sandwiches-2.jpg",
    n: 11,
  },
  {
    id: "clkji",
    name: "Sandwiches",
    subtitle: "Pork",
    price: 25,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/sandwiches-3.jpg",
    n: 12,
  },
  {
    id: "ckujoihj",
    name: "Sandwiches",
    subtitle: "Turkey",
    price: 300,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/sandwiches-4.jpg",
    n: 13,
  },
  {
    id: "csewrq",
    name: "Sandwiches",
    subtitle: "Veggie",
    price: 65,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/sandwiches-5.jpg",
    n: 14,
  },
/* block 4rd group */
  {
    id: "duhykjh",
    name: "Drinks",
    subtitle: "Coca-Cola",
    price: 45,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/drink-1.jpg",
    n: 15,
  },
  {
    id: "djhgy",
    name: "Drinks",
    subtitle: "Diet-Coke",
    price: 100,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/drink-2.jpg",
    n: 16,
  },
  {
    id: "djhtgy",
    name: "Drinks",
    subtitle: "Coke-zero",
    price: 25,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/drink-3.jpg",
    n: 17,
  },
  {
    id: "dhtgyu",
    name: "Drinks",
    subtitle: "Minda",
    price: 300,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/drink-4.jpg",
    n: 18,
  },
  {
    id: "drewpoi",
    name: "Drinks",
    subtitle: "SpecialPepsi",
    price: 65,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
    img: "images/drink-5.jpg",
    n: 19,
  },
];